name: Reforestation 🌱

on:
  workflow_dispatch:
  push:
    branches: ['main']
  schedule:
    # at minute 0 past hour 7, 8, 9, 10, and 11
    - cron: "0 7,8,9,10,11 * * *"

jobs:
  reforestation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Modify Last Update
        run: |
          chmod +x ./reforestation/run.sh
          ./reforestation/run.sh

      - name: Commit
        run: |
          git config --local user.email "gagas.repository@gmail.com"
          git config --local user.name "haiigas"
          git add --all

          date=$(date '+%Y-%m-%d %H:%M:%S')
          git commit -m "it's green [$date]"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
